# Generated by Django 4.2.13 on 2024-06-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsportal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Автор", "verbose_name_plural": "Авторы"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "Публикация", "verbose_name_plural": "Публикации"},
        ),
        migrations.AlterModelOptions(
            name="postcategory",
            options={
                "verbose_name": "Категория публикации",
                "verbose_name_plural": "Категории публикаций",
            },
        ),
    ]
